### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by mogeko** [aureliojargas/clitest#50]
Hey, guys!

Thank you for your great contribution!

This script is very helpful for me. Therefore, I hope to install it by Homebrew in my Mac. To this end, I opened a [PR](https://github.com/Homebrew/homebrew-core/pull/117676) to the Homebrew team. But it seems that this project has not been updated for 2 years, so Homebrew's reviewers want to **confirm that you are still maintaining the project**.

**Comment by aureliojargas** [comment]
Hi @mogeko,

Thanks for your message and for your time investment in getting clitest into brew. ❤️ 

Yes, clitest is still maintained.

This is a one-man project that started [almost 10 years ago](https://github.com/aureliojargas/clitest/commit/761cb4aa39fea3a30b3b41e8efbc081e6a196c7c). At this point, I consider it stable and full-featured. That's why there's not too much activity in the repository. Regardless, bug reports and feature requests are welcome!

I use clitest as the test runner in my other open source projects, so I have interest in keeping it working for the long run. Some examples:

- https://github.com/funcoeszz/funcoeszz/blob/98bee0c092c448cfa0fe241ab63c1fc5b945eb60/Makefile#L42-L45
- https://github.com/aureliojargas/txt2regex/blob/0f4199127225f021ef3825f3c43ab450748f32dc/Makefile#L77-L79
- https://github.com/aureliojargas/sedsed/blob/8fa4e7f4b6a7f6ab7b4655bb1a4a6502ff10f68f/Makefile#L27-L29
- https://github.com/aureliojargas/sedparse/blob/dc49fe00a3c6977bed4d4ddd9aa7955552d2cd01/Makefile#L41-L43
- https://github.com/aureliojargas/replace/blob/047315a2a7696b4af62b8ead444ff88f46009757/Makefile#L15-L17

As you can see in those Makefiles, I usually download clitest directly from GitHub, since the whole program is in a single shell script file. It may also be an option for you, just in case brew does not accept it.

**Comment by mogeko** [comment]
Thank you for your reply!

**Comment by aureliojargas** [comment]
BTW, version 0.5.0 was just released:
https://github.com/aureliojargas/clitest/releases/tag/0.5.0

**Comment by mogeko** [comment]
Thank you for your reminder, @aureliojargas

And thank you again for developing this great software!

When I was about to start updating the Homebrew Formula, I found that someone had already done what I wanted to do: https://github.com/Homebrew/homebrew-core/pull/134705

This is the charm of open source!🎉

**Comment by aureliojargas** [comment]
Wow, that was fast! 😮 
Thanks for letting me know.
